name: Mobile iOS Tests

on:
  push:
    branches: [main, master]
    paths:
      - mobile/**
  pull_request:
    branches: [master]
    paths:
      - mobile/**

jobs:
  build:
    name: iOS Test
    runs-on: macos-14
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
      - name: Set up applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install dependencies
        run: npm ci
      - name: Install CocoaPods
        run: cd ios && pod install
      - name: Run Detox build
        run: npx detox build --configuration ios.sim.debug
      - name: Run Detox Test
        run: |
          npx expo start &
          sleep 5 && npx detox test --configuration ios.sim.debug --headless
