name: Mobile Android Tests

on:
  push:
    branches: [main, master]
    paths:
      - mobile/**
  pull_request:
    branches: [master]
    paths:
      - mobile/**

env:
  ANDROID_EMU_ARCH: x86_64
  ANDROID_EMU_API_LEVEL: 34
  ANDROID_EMU_NAME: Pixel_7_API_34_x86

jobs:
  build:
    name: Android Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"
      - name: Install dependencies
        run: npm ci
      - name: Cache Detox build
        id: cache-detox-build
        uses: actions/cache@v3
        with:
          path: android/app/build
          key: ${{ runner.os }}-detox-build
          restore-keys: |
            ${{ runner.os }}-detox-build
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.ANDROID_EMU_API_LEVEL }}
      - name: Run Detox Build
        run: |
          chmod +x android/gradlew
          npx detox build --configuration android.emu.debug
      - name: Run Detox Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_EMU_API_LEVEL }}
          arch: ${{ env.ANDROID_EMU_ARCH }}
          avd-name: ${{ env.ANDROID_EMU_NAME }}
          script: |
            npx expo start &
            sleep 5 && npx detox test --configuration android.emu.debug --headless
